language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
matrix:
  allow_failures:
    - compiler: gcc
sudo: false
script:
  - python minipkg.py
  - source ~/.bash_profile
after_success:
  - pkgin list
after_failure:
  - cat *-log.txt
