language: c
os:
  - linux
  - osx
compiler:
  - clang
sudo: false
script:
  - python minipkg.py
  - source ~/.minipkg_profile
  - export PKG_PATH="$HOME/usr/pkgsrc/packages/All"
  - pkg_add autoconf
  - pkg_add automake
  - pkg_add bzip2
  - pkg_add clang
  - pkg_add cmake
  - pkg_add coccinelle
  - pkg_add curl
  - pkg_add cython
  - pkg_add fftw
  - pkg_add frama-c
  - pkg_add gmake
  - pkg_add gsed
  - pkg_add gzip
  - pkg_add libarchive
  - pkg_add libtool-base
  - pkg_add python
  - pkg_add python-numpy
  - pkg_add python-pillow
  - pkg_add python-setuptools
  - pkg_add python-wheel
  - pkg_add scons
  - pkg_add xz
  - pkg_add zlib
after_success:
  - pkg_info
  - autoconf --version
  - automake --version
  - bzip2 --version
  - clang --version
  - cmake --version
  - spatch --version
  - curl --version
  - cython --version
  - frama-c --version
  - gmake --version
  - gsed --version
  - gzip --version
  - bsdtar --version
  - libtool --version
  - python --version
  - python -c "import numpy; print(numpy.__version__)"
  - python -c "import PIL; print(PIL.__version__)"
  - scons --version
  - xz --version
after_failure:
  - cat pkgsrc-bootstrap-log.txt
  - cat ~/*-log.txt
