language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
matrix:
  allow_failures:
    - compiler: gcc
sudo: false
addons:
  apt:
    packages:
      - python-minimal
install:
  - python <(curl http://minipkg.eliteraspberries.com/minipkg.py)
  - source ~/.bash_profile
script:
  - pkg_info
after_failure:
  - cat *-log.txt
