language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
sudo: false
script:
  - python minipkg.py
  - source ~/.minipkg_profile
after_success:
  - pkg_info
after_failure:
  - cat pkgsrc-bootstrap-log.txt
