language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
sudo: false
addons:
  apt:
    packages:
      - python-minimal
install:
  - python <(curl https://www.eliteraspberries.com/minipkg.py)
  - source ~/.bash_profile
script:
  - pkg_info
after_failure:
  - cat *-log.txt
