language: c
os:
  - linux
  - osx
compiler:
  - clang
sudo: false
script:
  - python minipkg.py
  - source ~/.minipkg_profile
after_success:
  - pkg_info
  - bzip2 --version
  - gtar --version
  - gzip --version
  - xz --version
  - gmake --version
  - libtool --version
  - frama-c --version
  - spatch --version
  - python --version
  - cmake --version
  - clang --version
  - cython --version
  - scons --version
after_failure:
  - cat ~/*-log.txt
